### POST Request to test the api
POST http://localhost:3000/calendar/query
Content-Type: application/json

{
  "date": "2024-05-03", 
  "products": ["SolarPanels", "Heatpumps"], 
  "language": "German", 
  "rating": "Gold"
}

###