version: '3.4'

x-database-details: &database-details
  Database__Host: enpal-coding-challenge-db
  Database__Port: 5432
  Database__Name: coding-challenge
  Database__User: postgress
  Database__Password: mypassword123!

services:
  appointmentsystem-api:
    build:
      context: .
      dockerfile: AppointmentSystem.Api/Dockerfile
    environment:
      <<: [*database-details]
    networks:
      - appointment-system-network
    ports:
      - "3000:5049"
    depends_on:
      - enpal-coding-challenge-db  
  
  appointmentsystem-migrations:
    build:
      context: .
      dockerfile: AppointmentSystem.Migrations/Dockerfile
    environment:
      <<: [*database-details]
    networks:
      - appointment-system-network
    restart: on-failure
      
  enpal-coding-challenge-db:
    image: postgres:16  
    environment:
      POSTGRES__DB: postgress
      POSTRGRES__PASSWORD: mypassword123!
    ports:
      - "5432:5432"
    networks:
      - appointment-system-network
        
networks:
  appointment-system-network:
    driver: bridge
