version: '3.4'

x-dbserver-details: &dbserver
  DB_HOST: enpal-coding-challenge-db
  DB_PORT: 5432
  
x-database-details: &database
  POSTGRES_DB: coding-challenge
  POSTGRES_USER: postgress
  POSTGRES_PASSWORD: mypassword123!

services:
  appointmentsystem-api:
    build:
      context: .
      dockerfile: AppointmentSystem.Api/Dockerfile
    environment:
      <<: *dbserver
      <<: *database
    networks:
      - appointment-system-network
    ports:
      - "3000:5049"
    depends_on:
      - enpal-coding-challenge-db  
  
  appointmentsystem-migrations:
    build:
      context: .
      dockerfile: AppointmentSystem.Migrations/Dockerfile
    environment:
      <<: *dbserver
      <<: *database
    networks:
      - appointment-system-network
    restart: on-failure
      
  enpal-coding-challenge-db:
    image: postgres:16  
    environment:
      <<: *database
    ports:
      - "5432:5432"
    networks:
      - appointment-system-network
        
networks:
  appointment-system-network:
    driver: bridge
